apiVersion: apps/v1
kind: Deployment
metadata:
  name: depistage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depistage
  template:
    metadata:
      labels:
        app: depistage
    spec:
      containers:
      - name: depistage-container
        image: nadaikram/depistage-image:latest